services:
  server:
    image: ${IMAGE}:latest
    container_name: ${APP_NAME}
    restart: unless-stopped
    ports:
      - '${PORT}:3000'
    environment:
      - TZ=Asia/Shanghai
    env_file:
      - .env
    volumes:
      - printer_uploads:/app/uploads

volumes:
  printer_uploads:
